<?php
/*
* Implements hook_ctools_plugin_directory().
*/

include_once 'badistro_bloques.inc';

function badistro_bloques_ctools_plugin_directory($owner, $plugin_type) {
   if ($owner == 'ctools' && $plugin_type == 'content_types') {
     return 'plugins/' . $plugin_type;
   }
 }

function badistro_theme($existing, $type, $theme, $path) {
  return array(
    'badistro_bloques_alerta' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_alerta'
    ),
    'badistro_bloques_carrousel' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_carrousel'
    ),
    'badistro_bloques_campo_categoria_noticia' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_campo_categoria_noticia'
    ),
    'badistro_bloques_campo_costo' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_campo_costo'
    ),
    'badistro_bloques_campo_links_relacionados' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_campo_links_relacionados'
    ),
    'badistro_bloques_campo_paginas_relacionadas' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_campo_paginas_relacionadas'
    ),
    'badistro_bloques_campo_requisitos' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_campo_requisitos'
    ),
    'badistro_bloques_campo_siglas_area' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_campo_siglas_area'
    ),
    'badistro_bloques_campo_tags' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_campo_tags'
    ),
    'badistro_bloques_campo_tipo_tramite' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_campo_tipo_tramite'
    ),
    'badistro_bloques_galeria_imagenes_min' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_galeria_imagenes_min'
    ),
    'badistro_bloques_galeria_imagenes_min_item' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_galeria_imagenes_min_item'
    ),
    'badistro_bloques_listado_vertical' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_listado_vertical'
    ),
    'badistro_bloques_listado_vertical_item' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_listado_vertical_item'
    ),
    'badistro_bloques_listado_horizontal' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_listado_horizontal'
    ),
    'badistro_bloques_listado_horizontal_item' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_listado_horizontal_item'
    ),
    'badistro_bloques_listado_destacado_vertical' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_listado_destacado_vertical'
    ),
    'badistro_bloques_listado_destacado_vertical_item' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_listado_destacado_vertical_item'
    ),
    'badistro_bloques_listado_destacado_horizontal' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_listado_destacado_horizontal'
    ),
    'badistro_bloques_listado_destacado_horizontal_item' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_listado_destacado_horizontal_item'
    ),
    'badistro_bloques_listado_con_imagen_vertical' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_listado_con_imagen_vertical'
    ),
    'badistro_bloques_listado_con_imagen_vertical_item' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_listado_con_imagen_vertical_item'
    ),
    'badistro_bloques_listado_con_imagen_horizontal' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_listado_con_imagen_horizontal'
    ),
    'badistro_bloques_listado_con_imagen_horizontal_item' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_listado_con_imagen_horizontal_item'
    ),
    'badistro_bloques_listado_vacio' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_listado_vacio'
    ),
    'badistro_bloques_imagen_destacada' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_imagen_destacada'
    ),
    'badistro_bloques_titulo' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_titulo'
    ),
    'badistro_bloques_texto' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_texto'
    ),
    'badistro_bloques_shortcut' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_shortcut'
    ),
    'badistro_bloques_separador' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_separador'
    ),
    'badistro_bloques_redes_sociales_compartir' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_redes_sociales_compartir'
    ),
    'badistro_bloques_redes_sociales_timeline_facebook' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_redes_sociales_timeline_facebook'
    ),
    'badistro_bloques_redes_sociales_timeline_twitter' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_redes_sociales_timeline_twitter'
    ),
  );
}