<?php
/*
* Implements hook_ctools_plugin_directory().
*/

function badistro_bloques_ctools_plugin_directory($owner, $plugin_type) {
   if ($owner == 'ctools' && $plugin_type == 'content_types') {
     return 'plugins/' . $plugin_type;
   }
 }

function badistro_theme($existing, $type, $theme, $path) {
  return array(
    'badistro_bloques_alerta' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_alerta'
    ),
    'badistro_bloques_carrousel' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_carrousel'
    ),
    'badistro_bloques_listado_links' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_listado_links'
    ),
    'badistro_bloques_listado_links_con_imagen' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_listado_links_con_imagen'
    ),
    'badistro_bloques_imagen_destacada' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_imagen_destacada'
    ),
    'badistro_bloques_titulo' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_titulo'
    ),
    'badistro_bloques_texto' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_texto'
    ),
    'badistro_bloques_shortcut' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_shortcut'
    ),
    'badistro_bloques_separador' => array(
      'path' => drupal_get_path('module', 'badistro_bloques') . '/templates',
      'template' => 'badistro_bloques_separador'
    ),
  );
}