<?php
/**
 * @file
 * badistro_noticias.features.inc
 */

/**
 * Implements hook_node_info().
 */
function badistro_noticias_node_info() {
  $items = array(
    'noticia' => array(
      'name' => t('Noticia'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Título'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
